### ISSUE TITLE
Bug when attempting to play a song from TouTube Music

### ISSUE THREAD

**Issue by Sperryfreak01** [patrickkfkan/Volumio-YouTube.js#5]
info: [ytmusic-play] clearAddPlayTrack(): ytmusic/video@videoId=bOfLZiO2MZk@explodeTrackData=%7B%22videoId%22%3A%22bOfLZiO2MZk%22%2C%22title%22%3A%22Isis%20(feat.%20Logic)%22%2C%22artist%22%3A%22Joyner%20Lucas%22%2C%22album%22%3A%22ADHD%22%2C%22albumart%22%3A%22https%3A%2F%2Flh3.googleusercontent.com%2Fe0O9yAvUACTur751kdWM1ymznrMS72MpnniElZUVpaYjj9YNJQLA-sQLlthBWyjKe8dUtQhQolEb5AE%3Dw701-h701-l90-rj%22%2C%22playlistId%22%3A%22LM%22%2C%22autoplayContext%22%3A%7B%22playlistId%22%3A%22LM%22%2C%22continueFromVideoId%22%3A%22lhtn_zH-vNM%22%7D%7D@playlistId=LM@autoplayContext=%7B%22playlistId%22%3A%22LM%22%2C%22continueFromVideoId%22%3A%22lhtn_zH-vNM%22%7D
InnertubeError: MetadataScreen not found!
This is a bug, please report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues
    at Function.formatError (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:356:33)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:281:22)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:320:53)
    at new SingleColumnMusicWatchNextResults (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/classes/SingleColumnMusicWatchNextResults.js:11:41)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:276:32)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:320:53)
    at Function.parseResponse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:153:33)
    at Music. (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/core/Music.js:185:42)
    at Generator.next ()
    at fulfilled (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/core/Music.js:5:58)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  info: {
    sectionListRenderer: {
      contents: [Array],
      trackingParams: 'CDEQui8iEwid74Lnvsr7AhVM0sQKHfauAF4='
    }
  },
  date: 2022-11-25T23:31:47.457Z,
  version: '0.1.1-b.2'
}
error: [ytmusic-play] clearAddPlayTrack() error
error: Cannot read property 'as' of null

**Comment by 1dirtypanda** [comment]
I'm seeing the same issue. I noticed that when I am not signed in YTM plays music fine. Only after I sign in then I am not able to play music and these bugs come up.
